# Generated by Django 4.2 on 2023-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_q', models.CharField(max_length=32)),
                ('question', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=32)),
                ('parent', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=200)),
                ('answer_type', models.CharField(max_length=32)),
            ],
        ),
    ]
