# Generated by Django 4.2 on 2023-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
