# Generated by Django 4.2 on 2023-05-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diligence_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('num_map', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
                ('num_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
        ),
    ]
