# Generated by Django 4.2 on 2023-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='answer',
        ),
    ]
