# Generated by Django 4.2 on 2023-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
