# Generated by Django 4.2 on 2023-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_question_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
