# Generated by Django 4.2 on 2023-05-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_question_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ai_res',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
