# Generated by Django 4.2 on 2023-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_answer_ai_res_alter_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diligence',
            name='dili_name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='num_map',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_q',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
