# Generated by Django 4.2 on 2023-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_diligence_dili_name_alter_mapping_num_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alias',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
