# Generated by Django 4.2 on 2023-05-18 17:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_document_date_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
