# Generated by Django 4.2 on 2023-05-18 20:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_document_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='diligence',
            new_name='diligence_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(default=None, upload_to=api.models.upload_to),
        ),
    ]
