# Generated by Django 4.2 on 2023-05-18 20:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_diligence_document_diligence_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='diligence_id',
            new_name='diligence',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=api.models.upload_to),
        ),
    ]
