# Generated by Django 4.2 on 2023-05-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_diligence_id_document_diligence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
