# Generated by Django 4.2 on 2023-05-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_document_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='diligence',
            new_name='diligence_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
    ]
