# Generated by Django 4.2 on 2023-05-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_diligence_document_diligence_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='diligence_id',
            new_name='diligence',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
