# Generated by Django 4.2 on 2023-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_mapping_num_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCheckBox',
            fields=[
                ('num_q', models.CharField(max_length=16)),
                ('data_q', models.CharField(max_length=64)),
                ('num_map', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingRadio',
            fields=[
                ('num_q', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('num_map_yes', models.CharField(max_length=32, unique=True)),
                ('num_map_no', models.CharField(max_length=32, unique=True)),
                ('num_map_nan', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mapping',
            new_name='MappingText',
        ),
    ]
