# Generated by Django 4.2 on 2023-05-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_mappingcheckbox_mapping_checkbox_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapping_checkBox',
        ),
        migrations.DeleteModel(
            name='Mapping_radio',
        ),
        migrations.DeleteModel(
            name='Mapping_text',
        ),
    ]
