# Generated by Django 4.2 on 2023-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_mapping_checkbox_delete_mapping_radio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping_checkBox',
            fields=[
                ('num_q', models.CharField(max_length=16)),
                ('data_q', models.CharField(max_length=64)),
                ('num_map', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping_radio',
            fields=[
                ('num_q', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('num_map_yes', models.CharField(max_length=32, unique=True)),
                ('num_map_no', models.CharField(max_length=32, unique=True)),
                ('num_map_nan', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping_text',
            fields=[
                ('num_map', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('num_q', models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
