# Generated by Django 4.2 on 2023-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_mapping_radio_num_map_nan'),
    ]

    operations = [
        migrations.AddField(
            model_name='diligence',
            name='ici',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
