# Generated by Django 4.2 on 2023-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_diligence_ici'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_confidence',
            field=models.FloatField(null=True),
        ),
    ]
