# Generated by Django 4.2 on 2023-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_answer_ai_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='document_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
