# Generated by Django 4.2 on 2023-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_answer_user_alter_document_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ai_res_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
