# Generated by Django 4.2 on 2023-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_answer_ai_res_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping_radio',
            name='num_map_nan',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
